services:
  identity-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: identity-service
    command: ["./server", "grpc-gw-server"]
    ports:
      - "3031:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
