sonar.projectKey=bricams-identity-service:project
sonar.projectName=BRICaMS Identity Service
sonar.projectVersion=1.0

# Only source code (exclude test files)
sonar.sources=.
sonar.exclusions=**/*_test.go

# Define test files
sonar.tests=.
sonar.inclusions=**/*_test.go

# Go specific
sonar.go.tests=**/*_test.go
