// Code generated by hand (no protoc). DO NOT EDIT.
// source: saving_api.proto

package saving_service

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// SavingServiceServer is the server API for SavingService service.
type SavingServiceServer interface {
	GetExchangeRates(context.Context, *GetExchangeRatesRequest) (*ExchangeRateListResponse, error)
	GetInterestRates(context.Context, *GetInterestRatesRequest) (*InterestRateListResponse, error)
	GetBranches(context.Context, *GetBranchesRequest) (*BranchListResponse, error)
}

// UnimplementedSavingServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSavingServiceServer struct{}

func (UnimplementedSavingServiceServer) GetExchangeRates(context.Context, *GetExchangeRatesRequest) (*ExchangeRateListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchangeRates not implemented")
}
func (UnimplementedSavingServiceServer) GetInterestRates(context.Context, *GetInterestRatesRequest) (*InterestRateListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterestRates not implemented")
}
func (UnimplementedSavingServiceServer) GetBranches(context.Context, *GetBranchesRequest) (*BranchListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBranches not implemented")
}

// SavingServiceClient is the client API for SavingService service.
type SavingServiceClient interface {
	GetExchangeRates(ctx context.Context, in *GetExchangeRatesRequest, opts ...grpc.CallOption) (*ExchangeRateListResponse, error)
	GetInterestRates(ctx context.Context, in *GetInterestRatesRequest, opts ...grpc.CallOption) (*InterestRateListResponse, error)
	GetBranches(ctx context.Context, in *GetBranchesRequest, opts ...grpc.CallOption) (*BranchListResponse, error)
}

type savingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSavingServiceClient(cc grpc.ClientConnInterface) SavingServiceClient {
	return &savingServiceClient{cc}
}

const savingServiceName = "/saving.SavingService/"

func (c *savingServiceClient) GetExchangeRates(ctx context.Context, in *GetExchangeRatesRequest, opts ...grpc.CallOption) (*ExchangeRateListResponse, error) {
	out := new(ExchangeRateListResponse)
	err := c.cc.Invoke(ctx, savingServiceName+"GetExchangeRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingServiceClient) GetInterestRates(ctx context.Context, in *GetInterestRatesRequest, opts ...grpc.CallOption) (*InterestRateListResponse, error) {
	out := new(InterestRateListResponse)
	err := c.cc.Invoke(ctx, savingServiceName+"GetInterestRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingServiceClient) GetBranches(ctx context.Context, in *GetBranchesRequest, opts ...grpc.CallOption) (*BranchListResponse, error) {
	out := new(BranchListResponse)
	err := c.cc.Invoke(ctx, savingServiceName+"GetBranches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SavingService_ServiceDesc is the grpc.ServiceDesc for SavingService service.
var SavingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saving.SavingService",
	HandlerType: (*SavingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExchangeRates",
			Handler:    _SavingService_GetExchangeRates_Handler,
		},
		{
			MethodName: "GetInterestRates",
			Handler:    _SavingService_GetInterestRates_Handler,
		},
		{
			MethodName: "GetBranches",
			Handler:    _SavingService_GetBranches_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saving_api.proto",
}

func RegisterSavingServiceServer(s grpc.ServiceRegistrar, srv SavingServiceServer) {
	s.RegisterService(&SavingService_ServiceDesc, srv)
}

func _SavingService_GetExchangeRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingServiceServer).GetExchangeRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: savingServiceName + "GetExchangeRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingServiceServer).GetExchangeRates(ctx, req.(*GetExchangeRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingService_GetInterestRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterestRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingServiceServer).GetInterestRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: savingServiceName + "GetInterestRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingServiceServer).GetInterestRates(ctx, req.(*GetInterestRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingService_GetBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingServiceServer).GetBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: savingServiceName + "GetBranches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingServiceServer).GetBranches(ctx, req.(*GetBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}
