services:
  bff-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bff-service
    ports:
      - "3000:3000"
      - "9090:9090"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
