sonar.projectKey=bankease-bff-service:project
sonar.projectName=BankEase BFF Service
sonar.projectVersion=1.0

sonar.sources=server
sonar.tests=server
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/protogen/**,**/proto/**,**/vendor/**

sonar.go.coverage.reportPaths=coverage/coverage.out
sonar.go.tests.reportPaths=coverage/test-report.json
