// Code generated by hand (no protoc). DO NOT EDIT.
// User-profile service client stubs for BFF to call user-profile-service via gRPC.

package user_profile_service

import (
	"context"

	"google.golang.org/grpc"
)

// ── Payload types ──

type CreateProfileRequest struct {
	UserId       string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bank         string `protobuf:"bytes,2,opt,name=bank,proto3" json:"bank,omitempty"`
	Branch       string `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Name         string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CardNumber   string `protobuf:"bytes,5,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardProvider string `protobuf:"bytes,6,opt,name=card_provider,json=cardProvider,proto3" json:"card_provider,omitempty"`
	Balance      int64  `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency     string `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	AccountType  string `protobuf:"bytes,9,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
}

type GetProfileByIDRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

type GetProfileByUserIDRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

type UpdateProfileRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bank       string `protobuf:"bytes,2,opt,name=bank,proto3" json:"bank,omitempty"`
	Branch     string `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CardNumber string `protobuf:"bytes,5,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
}

type ProfileResponse struct {
	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bank         string `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	Branch       string `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	Name         string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	CardNumber   string `protobuf:"bytes,6,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardProvider string `protobuf:"bytes,7,opt,name=card_provider,json=cardProvider,proto3" json:"card_provider,omitempty"`
	Balance      int64  `protobuf:"varint,8,opt,name=balance,proto3" json:"balance"`
	Currency     string `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency"`
	AccountType  string `protobuf:"bytes,10,opt,name=account_type,json=accountType,proto3" json:"account_type"`
	Image        string `protobuf:"bytes,11,opt,name=image,proto3" json:"image"`
}

type GetAllMenusRequest struct{}

type GetMenusByAccountTypeRequest struct {
	AccountType string `protobuf:"bytes,1,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
}

type MenuItem struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index    int32  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title    string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	IconUrl  string `protobuf:"bytes,5,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsActive bool   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

type MenuListResponse struct {
	Menus []*MenuItem `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
}

type StandardResponse struct {
	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

// ── Client interface ──

type UserProfileServiceClient interface {
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	GetProfileByID(ctx context.Context, in *GetProfileByIDRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	GetProfileByUserID(ctx context.Context, in *GetProfileByUserIDRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*StandardResponse, error)
	GetAllMenus(ctx context.Context, in *GetAllMenusRequest, opts ...grpc.CallOption) (*MenuListResponse, error)
	GetMenusByAccountType(ctx context.Context, in *GetMenusByAccountTypeRequest, opts ...grpc.CallOption) (*MenuListResponse, error)
}

type userProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserProfileServiceClient(cc grpc.ClientConnInterface) UserProfileServiceClient {
	return &userProfileServiceClient{cc}
}

const userProfileServiceName = "/userprofile.UserProfileService/"

func (c *userProfileServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, userProfileServiceName+"CreateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) GetProfileByID(ctx context.Context, in *GetProfileByIDRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, userProfileServiceName+"GetProfileByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) GetProfileByUserID(ctx context.Context, in *GetProfileByUserIDRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, userProfileServiceName+"GetProfileByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*StandardResponse, error) {
	out := new(StandardResponse)
	err := c.cc.Invoke(ctx, userProfileServiceName+"UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) GetAllMenus(ctx context.Context, in *GetAllMenusRequest, opts ...grpc.CallOption) (*MenuListResponse, error) {
	out := new(MenuListResponse)
	err := c.cc.Invoke(ctx, userProfileServiceName+"GetAllMenus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) GetMenusByAccountType(ctx context.Context, in *GetMenusByAccountTypeRequest, opts ...grpc.CallOption) (*MenuListResponse, error) {
	out := new(MenuListResponse)
	err := c.cc.Invoke(ctx, userProfileServiceName+"GetMenusByAccountType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
