// Code generated by hand (no protoc). DO NOT EDIT.
// Payment service client stubs for BFF to call payment-service via gRPC.

package payment_service

import (
	"context"

	"google.golang.org/grpc"
)

// ── Payload types ──

type GetProvidersRequest struct{}

type ProviderItem struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
}

type ProviderListResponse struct {
	Providers []*ProviderItem `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
}

type GetInternetBillRequest struct{}

type InternetBillDetail struct {
	CustomerId  string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customerId"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Address     string `protobuf:"bytes,3,opt,name=address,proto3" json:"address"`
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phoneNumber"`
	Code        string `protobuf:"bytes,5,opt,name=code,proto3" json:"code"`
	From        string `protobuf:"bytes,6,opt,name=from,proto3" json:"from"`
	To          string `protobuf:"bytes,7,opt,name=to,proto3" json:"to"`
	InternetFee string `protobuf:"bytes,8,opt,name=internet_fee,json=internetFee,proto3" json:"internetFee"`
	Tax         string `protobuf:"bytes,9,opt,name=tax,proto3" json:"tax"`
	Total       string `protobuf:"bytes,10,opt,name=total,proto3" json:"total"`
}

type InternetBillResponse struct {
	Bill *InternetBillDetail `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

type GetCurrencyListRequest struct{}

type CurrencyEntry struct {
	Code  string  `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Label string  `protobuf:"bytes,2,opt,name=label,proto3" json:"label"`
	Rate  float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate"`
}

type CurrencyListResponse struct {
	Currencies []*CurrencyEntry `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
}

// ── Mobile Prepaid Types ──

type GetBeneficiariesRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId"`
}

type BeneficiaryItem struct {
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Phone  string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone"`
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
}

type BeneficiaryListResponse struct {
	Beneficiaries []*BeneficiaryItem `protobuf:"bytes,1,rep,name=beneficiaries,proto3" json:"beneficiaries,omitempty"`
}

type PrepaidPayRequest struct {
	CardId         string `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"cardId"`
	Phone          string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone"`
	Amount         int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount"`
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotencyKey"`
}

type PrepaidPayResponse struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Status    string `protobuf:"bytes,2,opt,name=status,proto3" json:"status"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message"`
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp"`
}

type AddBeneficiaryRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Phone     string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone"`
	Avatar    string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
}

type SearchBeneficiariesRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId"`
	Query     string `protobuf:"bytes,2,opt,name=query,proto3" json:"query"`
}

type GetPaymentCardsRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId"`
}

type PaymentCardItem struct {
	Id             string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	AccountId      string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"accountId"`
	HolderName     string   `protobuf:"bytes,3,opt,name=holder_name,json=holderName,proto3" json:"holderName"`
	CardLabel      string   `protobuf:"bytes,4,opt,name=card_label,json=cardLabel,proto3" json:"cardLabel"`
	MaskedNumber   string   `protobuf:"bytes,5,opt,name=masked_number,json=maskedNumber,proto3" json:"maskedNumber"`
	Balance        int64    `protobuf:"varint,6,opt,name=balance,proto3" json:"balance"`
	Currency       string   `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency"`
	Brand          string   `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand"`
	GradientColors []string `protobuf:"bytes,9,rep,name=gradient_colors,json=gradientColors,proto3" json:"gradientColors"`
}

type PaymentCardListResponse struct {
	Cards []*PaymentCardItem `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

type CreatePaymentCardRequest struct {
	AccountId      string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId"`
	HolderName     string   `protobuf:"bytes,2,opt,name=holder_name,json=holderName,proto3" json:"holderName"`
	CardLabel      string   `protobuf:"bytes,3,opt,name=card_label,json=cardLabel,proto3" json:"cardLabel"`
	MaskedNumber   string   `protobuf:"bytes,4,opt,name=masked_number,json=maskedNumber,proto3" json:"maskedNumber"`
	Balance        int64    `protobuf:"varint,5,opt,name=balance,proto3" json:"balance"`
	Currency       string   `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency"`
	Brand          string   `protobuf:"bytes,7,opt,name=brand,proto3" json:"brand"`
	GradientColors []string `protobuf:"bytes,8,rep,name=gradient_colors,json=gradientColors,proto3" json:"gradientColors"`
}

// ── Client interface ──

type PaymentServiceClient interface {
	GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*ProviderListResponse, error)
	GetInternetBill(ctx context.Context, in *GetInternetBillRequest, opts ...grpc.CallOption) (*InternetBillResponse, error)
	GetCurrencyList(ctx context.Context, in *GetCurrencyListRequest, opts ...grpc.CallOption) (*CurrencyListResponse, error)
	GetBeneficiaries(ctx context.Context, in *GetBeneficiariesRequest, opts ...grpc.CallOption) (*BeneficiaryListResponse, error)
	PrepaidPay(ctx context.Context, in *PrepaidPayRequest, opts ...grpc.CallOption) (*PrepaidPayResponse, error)
	AddBeneficiary(ctx context.Context, in *AddBeneficiaryRequest, opts ...grpc.CallOption) (*BeneficiaryItem, error)
	SearchBeneficiaries(ctx context.Context, in *SearchBeneficiariesRequest, opts ...grpc.CallOption) (*BeneficiaryListResponse, error)
	GetPaymentCards(ctx context.Context, in *GetPaymentCardsRequest, opts ...grpc.CallOption) (*PaymentCardListResponse, error)
	CreatePaymentCard(ctx context.Context, in *CreatePaymentCardRequest, opts ...grpc.CallOption) (*PaymentCardItem, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

const paymentServiceName = "/payment.PaymentService/"

func (c *paymentServiceClient) GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*ProviderListResponse, error) {
	out := new(ProviderListResponse)
	err := c.cc.Invoke(ctx, paymentServiceName+"GetProviders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetInternetBill(ctx context.Context, in *GetInternetBillRequest, opts ...grpc.CallOption) (*InternetBillResponse, error) {
	out := new(InternetBillResponse)
	err := c.cc.Invoke(ctx, paymentServiceName+"GetInternetBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetCurrencyList(ctx context.Context, in *GetCurrencyListRequest, opts ...grpc.CallOption) (*CurrencyListResponse, error) {
	out := new(CurrencyListResponse)
	err := c.cc.Invoke(ctx, paymentServiceName+"GetCurrencyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetBeneficiaries(ctx context.Context, in *GetBeneficiariesRequest, opts ...grpc.CallOption) (*BeneficiaryListResponse, error) {
	out := new(BeneficiaryListResponse)
	err := c.cc.Invoke(ctx, paymentServiceName+"GetBeneficiaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) PrepaidPay(ctx context.Context, in *PrepaidPayRequest, opts ...grpc.CallOption) (*PrepaidPayResponse, error) {
	out := new(PrepaidPayResponse)
	err := c.cc.Invoke(ctx, paymentServiceName+"PrepaidPay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) AddBeneficiary(ctx context.Context, in *AddBeneficiaryRequest, opts ...grpc.CallOption) (*BeneficiaryItem, error) {
	out := new(BeneficiaryItem)
	err := c.cc.Invoke(ctx, paymentServiceName+"AddBeneficiary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) SearchBeneficiaries(ctx context.Context, in *SearchBeneficiariesRequest, opts ...grpc.CallOption) (*BeneficiaryListResponse, error) {
	out := new(BeneficiaryListResponse)
	err := c.cc.Invoke(ctx, paymentServiceName+"SearchBeneficiaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentCards(ctx context.Context, in *GetPaymentCardsRequest, opts ...grpc.CallOption) (*PaymentCardListResponse, error) {
	out := new(PaymentCardListResponse)
	err := c.cc.Invoke(ctx, paymentServiceName+"GetPaymentCards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreatePaymentCard(ctx context.Context, in *CreatePaymentCardRequest, opts ...grpc.CallOption) (*PaymentCardItem, error) {
	out := new(PaymentCardItem)
	err := c.cc.Invoke(ctx, paymentServiceName+"CreatePaymentCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
