// Code generated by hand (no protoc). DO NOT EDIT.
// Payment service client stubs for BFF to call payment-service via gRPC.

package payment_service

import (
	"context"

	"google.golang.org/grpc"
)

// ── Payload types ──

type GetProvidersRequest struct{}

type ProviderItem struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
}

type ProviderListResponse struct {
	Providers []*ProviderItem `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
}

type GetInternetBillRequest struct{}

type InternetBillDetail struct {
	CustomerId  string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customerId"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Address     string `protobuf:"bytes,3,opt,name=address,proto3" json:"address"`
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phoneNumber"`
	Code        string `protobuf:"bytes,5,opt,name=code,proto3" json:"code"`
	From        string `protobuf:"bytes,6,opt,name=from,proto3" json:"from"`
	To          string `protobuf:"bytes,7,opt,name=to,proto3" json:"to"`
	InternetFee string `protobuf:"bytes,8,opt,name=internet_fee,json=internetFee,proto3" json:"internetFee"`
	Tax         string `protobuf:"bytes,9,opt,name=tax,proto3" json:"tax"`
	Total       string `protobuf:"bytes,10,opt,name=total,proto3" json:"total"`
}

type InternetBillResponse struct {
	Bill *InternetBillDetail `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

type GetCurrencyListRequest struct{}

type CurrencyEntry struct {
	Code  string  `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Label string  `protobuf:"bytes,2,opt,name=label,proto3" json:"label"`
	Rate  float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate"`
}

type CurrencyListResponse struct {
	Currencies []*CurrencyEntry `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
}

// ── Client interface ──

type PaymentServiceClient interface {
	GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*ProviderListResponse, error)
	GetInternetBill(ctx context.Context, in *GetInternetBillRequest, opts ...grpc.CallOption) (*InternetBillResponse, error)
	GetCurrencyList(ctx context.Context, in *GetCurrencyListRequest, opts ...grpc.CallOption) (*CurrencyListResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

const paymentServiceName = "/payment.PaymentService/"

func (c *paymentServiceClient) GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*ProviderListResponse, error) {
	out := new(ProviderListResponse)
	err := c.cc.Invoke(ctx, paymentServiceName+"GetProviders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetInternetBill(ctx context.Context, in *GetInternetBillRequest, opts ...grpc.CallOption) (*InternetBillResponse, error) {
	out := new(InternetBillResponse)
	err := c.cc.Invoke(ctx, paymentServiceName+"GetInternetBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetCurrencyList(ctx context.Context, in *GetCurrencyListRequest, opts ...grpc.CallOption) (*CurrencyListResponse, error) {
	out := new(CurrencyListResponse)
	err := c.cc.Invoke(ctx, paymentServiceName+"GetCurrencyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
