services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "8082:8082"
      - "9304:9304"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
