// Code generated by hand (no protoc). DO NOT EDIT.
// source: payment_payload.proto

package payment_service

// ── Provider Messages ──

type GetProvidersRequest struct{}

type ProviderItem struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
}

func (x *ProviderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *ProviderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProviderListResponse struct {
	Providers []*ProviderItem `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
}

func (x *ProviderListResponse) GetProviders() []*ProviderItem {
	if x != nil {
		return x.Providers
	}
	return nil
}

// ── Internet Bill Messages ──

type GetInternetBillRequest struct{}

type InternetBillDetail struct {
	CustomerId  string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customerId"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Address     string `protobuf:"bytes,3,opt,name=address,proto3" json:"address"`
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phoneNumber"`
	Code        string `protobuf:"bytes,5,opt,name=code,proto3" json:"code"`
	From        string `protobuf:"bytes,6,opt,name=from,proto3" json:"from"`
	To          string `protobuf:"bytes,7,opt,name=to,proto3" json:"to"`
	InternetFee string `protobuf:"bytes,8,opt,name=internet_fee,json=internetFee,proto3" json:"internetFee"`
	Tax         string `protobuf:"bytes,9,opt,name=tax,proto3" json:"tax"`
	Total       string `protobuf:"bytes,10,opt,name=total,proto3" json:"total"`
}

func (x *InternetBillDetail) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}
func (x *InternetBillDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *InternetBillDetail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}
func (x *InternetBillDetail) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}
func (x *InternetBillDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}
func (x *InternetBillDetail) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}
func (x *InternetBillDetail) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}
func (x *InternetBillDetail) GetInternetFee() string {
	if x != nil {
		return x.InternetFee
	}
	return ""
}
func (x *InternetBillDetail) GetTax() string {
	if x != nil {
		return x.Tax
	}
	return ""
}
func (x *InternetBillDetail) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type InternetBillResponse struct {
	Bill *InternetBillDetail `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *InternetBillResponse) GetBill() *InternetBillDetail {
	if x != nil {
		return x.Bill
	}
	return nil
}

// ── Currency Messages ──

type GetCurrencyListRequest struct{}

type CurrencyEntry struct {
	Code  string  `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Label string  `protobuf:"bytes,2,opt,name=label,proto3" json:"label"`
	Rate  float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate"`
}

func (x *CurrencyEntry) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}
func (x *CurrencyEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}
func (x *CurrencyEntry) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type CurrencyListResponse struct {
	Currencies []*CurrencyEntry `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
}

func (x *CurrencyListResponse) GetCurrencies() []*CurrencyEntry {
	if x != nil {
		return x.Currencies
	}
	return nil
}

// ── Mobile Prepaid Messages ──

type GetBeneficiariesRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId"`
}

func (x *GetBeneficiariesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type BeneficiaryItem struct {
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Phone  string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone"`
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
}

func (x *BeneficiaryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *BeneficiaryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *BeneficiaryItem) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}
func (x *BeneficiaryItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type BeneficiaryListResponse struct {
	Beneficiaries []*BeneficiaryItem `protobuf:"bytes,1,rep,name=beneficiaries,proto3" json:"beneficiaries,omitempty"`
}

func (x *BeneficiaryListResponse) GetBeneficiaries() []*BeneficiaryItem {
	if x != nil {
		return x.Beneficiaries
	}
	return nil
}

type PrepaidPayRequest struct {
	CardId         string `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"cardId"`
	Phone          string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone"`
	Amount         int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount"`
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotencyKey"`
}

func (x *PrepaidPayRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}
func (x *PrepaidPayRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}
func (x *PrepaidPayRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}
func (x *PrepaidPayRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PrepaidPayResponse struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Status    string `protobuf:"bytes,2,opt,name=status,proto3" json:"status"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message"`
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp"`
}

func (x *PrepaidPayResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *PrepaidPayResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}
func (x *PrepaidPayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}
func (x *PrepaidPayResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// ── Add Beneficiary Messages ──

type AddBeneficiaryRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Phone     string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone"`
	Avatar    string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
}

func (x *AddBeneficiaryRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}
func (x *AddBeneficiaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *AddBeneficiaryRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}
func (x *AddBeneficiaryRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// ── Search Beneficiary Messages ──

type SearchBeneficiariesRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId"`
	Query     string `protobuf:"bytes,2,opt,name=query,proto3" json:"query"`
}

func (x *SearchBeneficiariesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}
func (x *SearchBeneficiariesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// ── Payment Card Messages ──

type GetPaymentCardsRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId"`
}

func (x *GetPaymentCardsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type PaymentCardItem struct {
	Id             string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	AccountId      string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"accountId"`
	HolderName     string   `protobuf:"bytes,3,opt,name=holder_name,json=holderName,proto3" json:"holderName"`
	CardLabel      string   `protobuf:"bytes,4,opt,name=card_label,json=cardLabel,proto3" json:"cardLabel"`
	MaskedNumber   string   `protobuf:"bytes,5,opt,name=masked_number,json=maskedNumber,proto3" json:"maskedNumber"`
	Balance        int64    `protobuf:"varint,6,opt,name=balance,proto3" json:"balance"`
	Currency       string   `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency"`
	Brand          string   `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand"`
	GradientColors []string `protobuf:"bytes,9,rep,name=gradient_colors,json=gradientColors,proto3" json:"gradientColors"`
}

func (x *PaymentCardItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *PaymentCardItem) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}
func (x *PaymentCardItem) GetHolderName() string {
	if x != nil {
		return x.HolderName
	}
	return ""
}
func (x *PaymentCardItem) GetCardLabel() string {
	if x != nil {
		return x.CardLabel
	}
	return ""
}
func (x *PaymentCardItem) GetMaskedNumber() string {
	if x != nil {
		return x.MaskedNumber
	}
	return ""
}
func (x *PaymentCardItem) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}
func (x *PaymentCardItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}
func (x *PaymentCardItem) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}
func (x *PaymentCardItem) GetGradientColors() []string {
	if x != nil {
		return x.GradientColors
	}
	return nil
}

type PaymentCardListResponse struct {
	Cards []*PaymentCardItem `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *PaymentCardListResponse) GetCards() []*PaymentCardItem {
	if x != nil {
		return x.Cards
	}
	return nil
}

type CreatePaymentCardRequest struct {
	AccountId      string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId"`
	HolderName     string   `protobuf:"bytes,2,opt,name=holder_name,json=holderName,proto3" json:"holderName"`
	CardLabel      string   `protobuf:"bytes,3,opt,name=card_label,json=cardLabel,proto3" json:"cardLabel"`
	MaskedNumber   string   `protobuf:"bytes,4,opt,name=masked_number,json=maskedNumber,proto3" json:"maskedNumber"`
	Balance        int64    `protobuf:"varint,5,opt,name=balance,proto3" json:"balance"`
	Currency       string   `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency"`
	Brand          string   `protobuf:"bytes,7,opt,name=brand,proto3" json:"brand"`
	GradientColors []string `protobuf:"bytes,8,rep,name=gradient_colors,json=gradientColors,proto3" json:"gradientColors"`
}

func (x *CreatePaymentCardRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}
func (x *CreatePaymentCardRequest) GetHolderName() string {
	if x != nil {
		return x.HolderName
	}
	return ""
}
func (x *CreatePaymentCardRequest) GetCardLabel() string {
	if x != nil {
		return x.CardLabel
	}
	return ""
}
func (x *CreatePaymentCardRequest) GetMaskedNumber() string {
	if x != nil {
		return x.MaskedNumber
	}
	return ""
}
func (x *CreatePaymentCardRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}
func (x *CreatePaymentCardRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}
func (x *CreatePaymentCardRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}
func (x *CreatePaymentCardRequest) GetGradientColors() []string {
	if x != nil {
		return x.GradientColors
	}
	return nil
}
