// Code generated by hand (no protoc). DO NOT EDIT.
// source: payment_payload.proto

package payment_service

// ── Provider Messages ──

type GetProvidersRequest struct{}

type ProviderItem struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
}

func (x *ProviderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *ProviderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProviderListResponse struct {
	Providers []*ProviderItem `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
}

func (x *ProviderListResponse) GetProviders() []*ProviderItem {
	if x != nil {
		return x.Providers
	}
	return nil
}

// ── Internet Bill Messages ──

type GetInternetBillRequest struct{}

type InternetBillDetail struct {
	CustomerId  string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customerId"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Address     string `protobuf:"bytes,3,opt,name=address,proto3" json:"address"`
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phoneNumber"`
	Code        string `protobuf:"bytes,5,opt,name=code,proto3" json:"code"`
	From        string `protobuf:"bytes,6,opt,name=from,proto3" json:"from"`
	To          string `protobuf:"bytes,7,opt,name=to,proto3" json:"to"`
	InternetFee string `protobuf:"bytes,8,opt,name=internet_fee,json=internetFee,proto3" json:"internetFee"`
	Tax         string `protobuf:"bytes,9,opt,name=tax,proto3" json:"tax"`
	Total       string `protobuf:"bytes,10,opt,name=total,proto3" json:"total"`
}

func (x *InternetBillDetail) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}
func (x *InternetBillDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *InternetBillDetail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}
func (x *InternetBillDetail) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}
func (x *InternetBillDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}
func (x *InternetBillDetail) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}
func (x *InternetBillDetail) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}
func (x *InternetBillDetail) GetInternetFee() string {
	if x != nil {
		return x.InternetFee
	}
	return ""
}
func (x *InternetBillDetail) GetTax() string {
	if x != nil {
		return x.Tax
	}
	return ""
}
func (x *InternetBillDetail) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type InternetBillResponse struct {
	Bill *InternetBillDetail `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *InternetBillResponse) GetBill() *InternetBillDetail {
	if x != nil {
		return x.Bill
	}
	return nil
}

// ── Currency Messages ──

type GetCurrencyListRequest struct{}

type CurrencyEntry struct {
	Code  string  `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Label string  `protobuf:"bytes,2,opt,name=label,proto3" json:"label"`
	Rate  float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate"`
}

func (x *CurrencyEntry) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}
func (x *CurrencyEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}
func (x *CurrencyEntry) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type CurrencyListResponse struct {
	Currencies []*CurrencyEntry `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
}

func (x *CurrencyListResponse) GetCurrencies() []*CurrencyEntry {
	if x != nil {
		return x.Currencies
	}
	return nil
}
