// Code generated by hand (no protoc). DO NOT EDIT.
// source: bff_api.proto

package bff_service

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// BffServiceServer is the server API for BffService service.
type BffServiceServer interface {
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error)
	GetMyProfile(context.Context, *GetMyProfileRequest) (*ProfileResponse, error)
	GetProfileByID(context.Context, *GetProfileByIDRequest) (*ProfileResponse, error)
	GetProfileByUserID(context.Context, *GetProfileByUserIDRequest) (*ProfileResponse, error)
	CreateProfile(context.Context, *CreateProfileRequest) (*ProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*StandardResponse, error)
	GetAllMenus(context.Context, *GetAllMenusRequest) (*MenuListResponse, error)
	GetMenusByAccountType(context.Context, *GetMenusByAccountTypeRequest) (*MenuListResponse, error)
	GetExchangeRates(context.Context, *GetExchangeRatesRequest) (*ExchangeRateListResponse, error)
	GetInterestRates(context.Context, *GetInterestRatesRequest) (*InterestRateListResponse, error)
	GetBranches(context.Context, *GetBranchesRequest) (*BranchListResponse, error)
	GetProviders(context.Context, *GetProvidersRequest) (*ProviderListResponse, error)
	GetInternetBill(context.Context, *GetInternetBillRequest) (*InternetBillResponse, error)
	GetCurrencyList(context.Context, *GetCurrencyListRequest) (*CurrencyListResponse, error)
}

// UnimplementedBffServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBffServiceServer struct{}

func (UnimplementedBffServiceServer) SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (UnimplementedBffServiceServer) SignIn(context.Context, *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedBffServiceServer) GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedBffServiceServer) GetMyProfile(context.Context, *GetMyProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyProfile not implemented")
}
func (UnimplementedBffServiceServer) GetProfileByID(context.Context, *GetProfileByIDRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileByID not implemented")
}
func (UnimplementedBffServiceServer) GetProfileByUserID(context.Context, *GetProfileByUserIDRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileByUserID not implemented")
}
func (UnimplementedBffServiceServer) CreateProfile(context.Context, *CreateProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedBffServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*StandardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedBffServiceServer) GetAllMenus(context.Context, *GetAllMenusRequest) (*MenuListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMenus not implemented")
}
func (UnimplementedBffServiceServer) GetMenusByAccountType(context.Context, *GetMenusByAccountTypeRequest) (*MenuListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenusByAccountType not implemented")
}
func (UnimplementedBffServiceServer) GetExchangeRates(context.Context, *GetExchangeRatesRequest) (*ExchangeRateListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchangeRates not implemented")
}
func (UnimplementedBffServiceServer) GetInterestRates(context.Context, *GetInterestRatesRequest) (*InterestRateListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterestRates not implemented")
}
func (UnimplementedBffServiceServer) GetBranches(context.Context, *GetBranchesRequest) (*BranchListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBranches not implemented")
}
func (UnimplementedBffServiceServer) GetProviders(context.Context, *GetProvidersRequest) (*ProviderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedBffServiceServer) GetInternetBill(context.Context, *GetInternetBillRequest) (*InternetBillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInternetBill not implemented")
}
func (UnimplementedBffServiceServer) GetCurrencyList(context.Context, *GetCurrencyListRequest) (*CurrencyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrencyList not implemented")
}

const bffServiceName = "/bff.BffService/"

// BffService_ServiceDesc is the grpc.ServiceDesc for BffService service.
var BffService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bff.BffService",
	HandlerType: (*BffServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "SignUp", Handler: _BffService_SignUp_Handler},
		{MethodName: "SignIn", Handler: _BffService_SignIn_Handler},
		{MethodName: "GetMe", Handler: _BffService_GetMe_Handler},
		{MethodName: "GetMyProfile", Handler: _BffService_GetMyProfile_Handler},
		{MethodName: "GetProfileByID", Handler: _BffService_GetProfileByID_Handler},
		{MethodName: "GetProfileByUserID", Handler: _BffService_GetProfileByUserID_Handler},
		{MethodName: "CreateProfile", Handler: _BffService_CreateProfile_Handler},
		{MethodName: "UpdateProfile", Handler: _BffService_UpdateProfile_Handler},
		{MethodName: "GetAllMenus", Handler: _BffService_GetAllMenus_Handler},
		{MethodName: "GetMenusByAccountType", Handler: _BffService_GetMenusByAccountType_Handler},
		{MethodName: "GetExchangeRates", Handler: _BffService_GetExchangeRates_Handler},
		{MethodName: "GetInterestRates", Handler: _BffService_GetInterestRates_Handler},
		{MethodName: "GetBranches", Handler: _BffService_GetBranches_Handler},
		{MethodName: "GetProviders", Handler: _BffService_GetProviders_Handler},
		{MethodName: "GetInternetBill", Handler: _BffService_GetInternetBill_Handler},
		{MethodName: "GetCurrencyList", Handler: _BffService_GetCurrencyList_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bff_api.proto",
}

func RegisterBffServiceServer(s grpc.ServiceRegistrar, srv BffServiceServer) {
	s.RegisterService(&BffService_ServiceDesc, srv)
}

func _BffService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "SignUp"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "SignIn"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetMe"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetMyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetMyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetMyProfile"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetMyProfile(ctx, req.(*GetMyProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetProfileByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetProfileByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetProfileByID"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetProfileByID(ctx, req.(*GetProfileByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetProfileByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetProfileByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetProfileByUserID"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetProfileByUserID(ctx, req.(*GetProfileByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "CreateProfile"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "UpdateProfile"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetAllMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMenusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetAllMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetAllMenus"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetAllMenus(ctx, req.(*GetAllMenusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetMenusByAccountType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenusByAccountTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetMenusByAccountType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetMenusByAccountType"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetMenusByAccountType(ctx, req.(*GetMenusByAccountTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetExchangeRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetExchangeRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetExchangeRates"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetExchangeRates(ctx, req.(*GetExchangeRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetInterestRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterestRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetInterestRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetInterestRates"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetInterestRates(ctx, req.(*GetInterestRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetBranches"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetBranches(ctx, req.(*GetBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetProviders"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetProviders(ctx, req.(*GetProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetInternetBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInternetBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetInternetBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetInternetBill"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetInternetBill(ctx, req.(*GetInternetBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffService_GetCurrencyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrencyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffServiceServer).GetCurrencyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bffServiceName + "GetCurrencyList"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffServiceServer).GetCurrencyList(ctx, req.(*GetCurrencyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}
