// Code generated by hand (no protoc). DO NOT EDIT.
// source: bff_payload.proto

package bff_service

// ── Auth Messages ──

type SignUpRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Phone    string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *SignUpRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type SignUpResponse struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *SignUpResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignUpResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SignInRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SignInRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInResponse struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Token    string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SignInResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignInResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignInResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetMeRequest struct{}

type GetMeResponse struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GetMeResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMeResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// ── Profile Messages ──

type GetMyProfileRequest struct{}

type GetProfileByIDRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProfileByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProfileByUserIDRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetProfileByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateProfileRequest struct {
	UserId       string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bank         string `protobuf:"bytes,2,opt,name=bank,proto3" json:"bank,omitempty"`
	Branch       string `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Name         string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CardNumber   string `protobuf:"bytes,5,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardProvider string `protobuf:"bytes,6,opt,name=card_provider,json=cardProvider,proto3" json:"card_provider,omitempty"`
	Balance      int64  `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency     string `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	AccountType  string `protobuf:"bytes,9,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *CreateProfileRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateProfileRequest) GetCardProvider() string {
	if x != nil {
		return x.CardProvider
	}
	return ""
}

func (x *CreateProfileRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateProfileRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateProfileRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

type UpdateProfileRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bank       string `protobuf:"bytes,2,opt,name=bank,proto3" json:"bank,omitempty"`
	Branch     string `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CardNumber string `protobuf:"bytes,5,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
}

func (x *UpdateProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProfileRequest) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *UpdateProfileRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

type ProfileResponse struct {
	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bank         string `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	Branch       string `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	Name         string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	CardNumber   string `protobuf:"bytes,6,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardProvider string `protobuf:"bytes,7,opt,name=card_provider,json=cardProvider,proto3" json:"card_provider,omitempty"`
	Balance      int64  `protobuf:"varint,8,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency     string `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	AccountType  string `protobuf:"bytes,10,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Image        string `protobuf:"bytes,11,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *ProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileResponse) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *ProfileResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *ProfileResponse) GetCardProvider() string {
	if x != nil {
		return x.CardProvider
	}
	return ""
}

func (x *ProfileResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ProfileResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProfileResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *ProfileResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// ── Menu Messages ──

type GetAllMenusRequest struct{}

type GetMenusByAccountTypeRequest struct {
	AccountType string `protobuf:"bytes,1,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
}

func (x *GetMenusByAccountTypeRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

type MenuItem struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index    int32  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title    string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	IconUrl  string `protobuf:"bytes,5,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsActive bool   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *MenuItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItem) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MenuItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MenuItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MenuItem) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *MenuItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type MenuListResponse struct {
	Menus []*MenuItem `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
}

func (x *MenuListResponse) GetMenus() []*MenuItem {
	if x != nil {
		return x.Menus
	}
	return nil
}

// ── Common Messages ──

type StandardResponse struct {
	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *StandardResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StandardResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ── Error Messages ──

type ErrorBodyResponse struct {
	Error   bool   `json:"error,omitempty"`
	Code    int32  `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
