// Code generated by hand (no protoc). DO NOT EDIT.
// source: user_profile_payload.proto

package user_profile_service

// ── Profile Messages ──

// CreateProfileRequest
type CreateProfileRequest struct {
	UserId       string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bank         string `protobuf:"bytes,2,opt,name=bank,proto3" json:"bank,omitempty"`
	Branch       string `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Name         string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CardNumber   string `protobuf:"bytes,5,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardProvider string `protobuf:"bytes,6,opt,name=card_provider,json=cardProvider,proto3" json:"card_provider,omitempty"`
	Balance      int64  `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency     string `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	AccountType  string `protobuf:"bytes,9,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Image        string `protobuf:"bytes,10,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *CreateProfileRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateProfileRequest) GetCardProvider() string {
	if x != nil {
		return x.CardProvider
	}
	return ""
}

func (x *CreateProfileRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateProfileRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateProfileRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateProfileRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// GetProfileByIDRequest
type GetProfileByIDRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProfileByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetProfileByUserIDRequest
type GetProfileByUserIDRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetProfileByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UpdateProfileRequest
type UpdateProfileRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bank       string `protobuf:"bytes,2,opt,name=bank,proto3" json:"bank,omitempty"`
	Branch     string `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CardNumber string `protobuf:"bytes,5,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
}

func (x *UpdateProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProfileRequest) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *UpdateProfileRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

// ProfileResponse
type ProfileResponse struct {
	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bank         string `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	Branch       string `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	Name         string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	CardNumber   string `protobuf:"bytes,6,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardProvider string `protobuf:"bytes,7,opt,name=card_provider,json=cardProvider,proto3" json:"card_provider,omitempty"`
	Balance      int64  `protobuf:"varint,8,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency     string `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	AccountType  string `protobuf:"bytes,10,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Image        string `protobuf:"bytes,11,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *ProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileResponse) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *ProfileResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *ProfileResponse) GetCardProvider() string {
	if x != nil {
		return x.CardProvider
	}
	return ""
}

func (x *ProfileResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ProfileResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProfileResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *ProfileResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// ── Menu Messages ──

// GetAllMenusRequest
type GetAllMenusRequest struct{}

// GetMenusByAccountTypeRequest
type GetMenusByAccountTypeRequest struct {
	AccountType string `protobuf:"bytes,1,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
}

func (x *GetMenusByAccountTypeRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

// MenuItem
type MenuItem struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index    int32  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title    string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	IconUrl  string `protobuf:"bytes,5,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsActive bool   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *MenuItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItem) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MenuItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MenuItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MenuItem) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *MenuItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// MenuListResponse
type MenuListResponse struct {
	Menus []*MenuItem `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
}

func (x *MenuListResponse) GetMenus() []*MenuItem {
	if x != nil {
		return x.Menus
	}
	return nil
}

// ── Search Messages ──

// GetExchangeRatesRequest
type GetExchangeRatesRequest struct{}

// ExchangeRateItem
type ExchangeRateItem struct {
	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Country     string  `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Currency    string  `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CountryCode string  `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Buy         float64 `protobuf:"fixed64,5,opt,name=buy,proto3" json:"buy,omitempty"`
	Sell        float64 `protobuf:"fixed64,6,opt,name=sell,proto3" json:"sell,omitempty"`
}

func (x *ExchangeRateItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *ExchangeRateItem) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}
func (x *ExchangeRateItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}
func (x *ExchangeRateItem) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}
func (x *ExchangeRateItem) GetBuy() float64 {
	if x != nil {
		return x.Buy
	}
	return 0
}
func (x *ExchangeRateItem) GetSell() float64 {
	if x != nil {
		return x.Sell
	}
	return 0
}

// ExchangeRateListResponse
type ExchangeRateListResponse struct {
	ExchangeRates []*ExchangeRateItem `protobuf:"bytes,1,rep,name=exchange_rates,json=exchangeRates,proto3" json:"exchange_rates,omitempty"`
}

func (x *ExchangeRateListResponse) GetExchangeRates() []*ExchangeRateItem {
	if x != nil {
		return x.ExchangeRates
	}
	return nil
}

// GetInterestRatesRequest
type GetInterestRatesRequest struct{}

// InterestRateItem
type InterestRateItem struct {
	Id      string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind    string  `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Deposit string  `protobuf:"bytes,3,opt,name=deposit,proto3" json:"deposit,omitempty"`
	Rate    float64 `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *InterestRateItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *InterestRateItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}
func (x *InterestRateItem) GetDeposit() string {
	if x != nil {
		return x.Deposit
	}
	return ""
}
func (x *InterestRateItem) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// InterestRateListResponse
type InterestRateListResponse struct {
	InterestRates []*InterestRateItem `protobuf:"bytes,1,rep,name=interest_rates,json=interestRates,proto3" json:"interest_rates,omitempty"`
}

func (x *InterestRateListResponse) GetInterestRates() []*InterestRateItem {
	if x != nil {
		return x.InterestRates
	}
	return nil
}

// GetBranchesRequest
type GetBranchesRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *GetBranchesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// BranchItem
type BranchItem struct {
	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Distance  string  `protobuf:"bytes,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Latitude  float64 `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *BranchItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *BranchItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *BranchItem) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}
func (x *BranchItem) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}
func (x *BranchItem) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// BranchListResponse
type BranchListResponse struct {
	Branches []*BranchItem `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
}

func (x *BranchListResponse) GetBranches() []*BranchItem {
	if x != nil {
		return x.Branches
	}
	return nil
}

// ── Common ──

// StandardResponse
type StandardResponse struct {
	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *StandardResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StandardResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}
