services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-profile-service
    ports:
      - "8080:8080"
      - "9302:9302"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
