services:
  db:
    image: postgres:17-alpine
    container_name: bankease-db
    environment:
      POSTGRES_USER: bankease
      POSTGRES_PASSWORD: bankease123
      POSTGRES_DB: bankease_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/db/migrations/001_init.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankease -d bankease_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-profile-service
    ports:
      - "8080:8080"
      - "9302:9302"
    environment:
      DATABASE_URL: postgres://bankease:bankease123@db:5432/bankease_db?sslmode=disable
      PORT: "8080"
      GRPC_PORT: "9302"
      AZURE_STORAGE_SAS_URL: https://plnsa.blob.core.windows.net/?sv=2025-11-05&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2026-04-11T14:56:36Z&st=2026-03-26T06:41:36Z&spr=https&sig=uqbKbqKFLDkoZX%2FxLosVhIardyUGotShuDGtHWv9yjE%3D
      AZURE_STORAGE_CONTAINER: images
      JWT_SECRET: secret
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
